<?php
/**
 * Created by PhpStorm.
 * User: eliottdes
 * Date: 18/12/17
 * Time: 18:34
 */

function outputGeneration ($options, $jsonFile) {

    switch ($options) {
        case 'array':
            echo "Array display:\n";
            print_r(arrayDisplay($jsonFile));

            break;

        case 'json':
            echo "Json display:\n";
            echo file_get_contents($jsonFile);

            break;

        case 'user':
            echo "User friendly display:\n";
            echo userFriendlyDisplay($jsonFile);

            break;

        default:
            echo "Unknow value. Please use either 'array', 'json' or 'user'.\n";
            break;
    }
}

function arrayDisplay ($jsonFile) {

    // Converting the json file in a workable array
    $data = json_decode(file_get_contents($jsonFile), true);

    $contracts = $data['contracts'];
    $providers = $data['providers'];
    $users = $data['users'];

    $output = array("bills" => array());

    for ($i = 0; $i < count($contracts); $i++) {
        for ($j = 0; $j < count($providers); $j++) {
            for ($k = 0; $k < count($users); $k++) {

                if ($contracts[$i]['provider_id'] == $providers[$j]['id'] && $contracts[$i]['user_id'] == $users[$k]['id']) {

                    if ($contracts[$i]['green'] == 1) {
                        $rawBill = $providers[$j]['price_per_kwh'] * ($users[$k]['yearly_consumption'] - $users[$k]['yearly_consumption'] * 0.05);
                    } else {
                        $rawBill = $providers[$j]['price_per_kwh'] * $users[$k]['yearly_consumption'];
                    }


                    if ($contracts[$i]['contract_length'] <= 1) {
                        $billedAmount = $rawBill - $rawBill * 0.1;
                    } elseif ($contracts[$i]['contract_length'] <= 3) {
                        $billedAmount = $rawBill - $rawBill * 0.2;
                    } else {
                        $billedAmount = $rawBill - $rawBill * 0.25;
                    }

                    $insurance_fee = ($contracts[$i]['contract_length'] * 365 * 0.05);

                    $provider_fee = $billedAmount - $insurance_fee;

                    $selectra_fee = round($provider_fee * (12.5 / 100), 2);

                    $output["bills"][$k]["commission"]['insurance_fee'] = $insurance_fee;
                    $output["bills"][$k]["commission"]['provider_fee'] = $provider_fee;
                    $output["bills"][$k]["commission"]['selectra_fee'] = $selectra_fee;

                    $output["bills"][$k]['id'] = $k + 1;
                    $output["bills"][$k]['price'] = $billedAmount;
                    $output["bills"][$k]['user_id'] = $users[$k]['id'];
                }
            }
        }
    }
    return $output;
}


function userFriendlyDisplay ($output) {
    $data = arrayDisplay($output);
    $display = "There are " . count($data['bills']) . " bills which have been generated by the input file:\n\n";

    for ($i = 0; $i < count($data['bills']); $i++) {
        $d = $data['bills'][$i];
        $display = $display . "     Bill n°" . $d['id'] . ":\n";
        $display = $display . "         The electrical bill of the user n°" . $d['user_id'] . " is set at " . $d['price'] . "$.\n";
        $display = $display . "         Provider fees are set at " . $d['commission']['insurance_fee'] . "$.\n";
        $display = $display . "         Insurance fees are set at " . $d['commission']['provider_fee'] . "$.\n";
        $display = $display . "         And Selectra fees are set at " . $d['commission']['selectra_fee'] . "$.\n\n";
    }
    return $display;
}